development:  
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5
  username: nicolaiahlefeldt
  password:

test:  
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5
  username: nicolaiahlefeldt
  password: